version: "3.8"

services:
  node:
    image: node
    volumes:
      - ~/github-dark-theme:/app
    ports:
      - "1337"
    tty: true
    depends_on:
      - postgres

  fiber:
    build: ./fiber
    volumes:
      - ~/app:/app
    tty: true
    depends_on:
      - postgres

  postgres:
    image: postgres
    volumes:
      - ~/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}